### ISSUE TITLE
When skip:true, this.saEvent() throws an error (eg, non production environments)

### ISSUE THREAD

**Issue by Chippd** [simpleanalytics/vue-plugin#16]
Forgive my noobness, I'm not a professional dev, I just bumped into this issue in my side project though. 
I see in the plugin, that the `window.sa_event` is only being added to the Vue prototype when `skip != true` [link](https://github.com/simpleanalytics/vue-plugin/blob/65fa0a33c6bffc8996cc5641f6ee857fa3416050/src/index.js#L42). 

That was throwing an error in my app when trying to track events. I didn't want to wrap every single event tracking call in my app within an `if(prod){//track the thing}`, so I'm using the below snippet in my main.js to get around this. 

I like that I can see that the event _would_ have been fired. 

```
// in main.js
// handle non production saEvent 
if(process.env.VUE_APP_NODE_ENV !== "production"){
  Vue.prototype.saEvent = function(thing){console.log(`would track ${thing}`)}
}
```

Just a suggestion, otherwise love you guys.

**Comment by Chippd** [comment]
Submitted pull request for this: https://github.com/simpleanalytics/vue-plugin/pull/17

**Comment by adriaandotcom** [comment]
Thanks for you PR, it's live at https://www.npmjs.com/package/simple-analytics-vue
