### ISSUE TITLE
ERR_CERT_COMMON_NAME_INVALID error

### ISSUE THREAD

**Issue by khrome83** [simpleanalytics/vue-plugin#3]
@adriaanvanrossum - I am getting the following error once I upgraded. I can see that it is trying to load from sa.domain.com/app.js correctly. 

Any clue?

`Failed to load resource: net::ERR_CERT_COMMON_NAME_INVALID`

**Comment by adriaandotcom** [comment]
Thanks for reporting!

Yesterday we had a downtime from 18:10 to 18:56 UTC. We will be emailing our customers about it today, but it seems like your time of posting didn't have downtime.

If you go to the `app.js` directly, does it work? I have a test domain for the script (https://api.adriaan.io/app.js) and API (https://api.adriaan.io/post). Do you get any error if you use those?

**Comment by khrome83** [comment]
Trying now, stay tuned.

**Comment by khrome83** [comment]
Ok so with your's it worked fine. With my domain, and the cname setup it fails...

This is what Edge Canary (chromium based) gives me.

<img width="689" alt="Screen Shot 2019-07-12 at 10 11 34 PM" src="https://user-images.githubusercontent.com/1844739/61166388-2ddcd980-a4f2-11e9-82aa-b4380c2a9ade.png">

**Comment by khrome83** [comment]
@adriaanvanrossum - I am reverting to your /app.js domain just to see if it's consistent. 

My guess is it has something to do with https?

**Comment by khrome83** [comment]
Double-checking our code. We are for sure using https on the request.

` el.src = 'https://' + domain + '/' + file + '.js';`

**Comment by adriaandotcom** [comment]
I found the problem. It's in our UI. It's not clear that you need to request the SSL after saving the subdomain. There is a link under the input field. I will fix this and make sure SSL is automatically requested after saving.

Thanks for looking into this! I fixed it now for your domain and it works now.

**Comment by khrome83** [comment]
Yeah, I just requested SSL (too many sure I understood) and this worked. 

I updated my site to point to my subdomain. Thank you for checking in on this, I really appreciate it.
