### ISSUE TITLE
Nuxt3 gives an error: Cannot set properties of undefined (setting 'saEvent')

### ISSUE THREAD

**Issue by stonetwig** [simpleanalytics/vue-plugin#42]
Hello,

I know that you are probably not supporting nuxt3 yet but I just want to give this a proper issue.

I modified the simple-analytics.js as per instruction to:

```
import SimpleAnalytics from "simple-analytics-vue";

export default defineNuxtPlugin((nuxtApp) => {
    nuxtApp.vueApp.use(SimpleAnalytics, { skip: process.env.NODE_ENV !== "production" });
});
```

But the plugin gives me the following error when starting the app:

```
[nuxt] [request error] Cannot set properties of undefined (setting 'saEvent')
  at handleSkipOrLocalhost (C:\code\my-app\node_modules\simple-analytics-vue\dist\index.js:37:25)
  at Object.install (C:\code\my-app\node_modules\simple-analytics-vue\dist\index.js:56:15)
```

Any clues if I can fix this in an easy manner?
Nuxt3 is about to be released so it would be nice to upgrade the plugin with proper support in due time.

Thanks in advance

**Comment by jamiecarter7** [comment]
+1

**Comment by lucasfischer** [comment]
Nuxt 3.0 is [stable now](https://nuxt.com/v3#announcing-nuxt-30-stable), so would be cool to get a fix for this ❤️

**Comment by adriaandotcom** [comment]
Vue 3 support should be available now: https://www.npmjs.com/package/simple-analytics-vue

**Comment by bradley-varol** [comment]
![image](https://user-images.githubusercontent.com/19194140/218998359-0fedf78d-7a84-443c-9b39-19544db9383c.png)
looks like prettier formatted the markdown 🤦🏻
